### PR TITLE
Fix httpie with last whalebrew

### PR DESCRIPTION
**Pull request by gerchardon**

### CODE REVIEW

**Comment by bfirsh** [comment]
Hmm - what broke?

**Comment by gerchardon** [comment]
because of https://github.com/bfirsh/whalebrew/pull/42 httpie need to have a configuration file or write one

**Comment by bfirsh** [comment]
Ah! Thanks. Perhaps it would make sense to pass that directory as a volume to ~/.httpie? Does that config file get used for much?

**Comment by gerchardon** [comment]
I never modify it so I don't know

**Pull request merged**
