### PR TITLE
[octodns] feat(GHCR): switch

### PR DESCRIPTION
**Pull request by eyenx**
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

### CODE REVIEW

**Comment by tjamet** [comment]
Hi!
nothing against, can you motivate the switch of base images?

**Comment by eyenx** [comment]
Dockerhub's new rate limiting.

**Comment by tjamet** [comment]
thanks!
I think for the time being we should be good with the rate limits from our as we are rarely pulling those images. Did you have to update on your side for more frequent pushes?

**Comment by eyenx** [comment]
Some people were hitting the limit behind enterprise proxy.

**Comment by eyenx** [comment]
> Some people were hitting the limit behind enterprise proxy.

also when doing lot's of DNS changes through CI, the runners were also hitting the limit.

**Comment by tjamet** [comment]
Thanks for the reasoning!
I will proceed to merge

Though, I tend to think that this problem:

> Some people were hitting the limit behind enterprise proxy

Is caused by where we push the images rather than from where we download them.

A first work-around it could be to install those packages from github though: https://github.com/orgs/whalebrew/packages?tab=packages&q=octodns

**Pull request merged**
