### PR TITLE
add whalebrew/packer

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
Adds `whalebrew/packer` ([https://packer.io]())

### CODE REVIEW

**Comment by bfirsh** [comment]
Thanks! Looks like the official hashicorp image works fine though, so I've opted for just using that: https://github.com/whalebrew/whalebrew-packages/commit/401fbf256b56e8f05b688e3b557aab1af5648462

**Comment by LongLiveCHIEF** [comment]
I recommend reconsidering.  See my comments in: https://github.com/hashicorp/docker-hub-images/pull/18.

Let me know what you think.

**Comment by bfirsh** [comment]
Is it the working directory that's the problem? I don't think that's an issue - I haven't set that in any of the other images.

**Comment by LongLiveCHIEF** [comment]
I see what you're saying.  We're already doing the volume mapping and setting the workdir, which resolves the issues with template interpolation and build output not being saved to the host.

Objections withdrawn. :thumbsup:

**Pull request closed without merging**
